language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install --use-mirrors numpy
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: python tests/count_tests.py