language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: pip install -r requirements.txt --use-mirrors --system-site-packages
# command to run tests
script: python tests/count_tests.py